"""Add consecutive column with default

Revision ID: 958e16abc4d4
Revises: db6be67b8d3b
Create Date: 2025-04-15 17:52:30.388365

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '958e16abc4d4'
down_revision = 'db6be67b8d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_card', schema=None) as batch_op:
        batch_op.drop_column('consecutive')

    # ### end Alembic commands ###
