"""Add FlashCard

Revision ID: db6be67b8d3b
Revises: 
Create Date: 2025-03-21 18:11:40.158583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6be67b8d3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leitner_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_hard', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_known', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('correct_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('wrong_count', sa.Integer(), nullable=False))
        batch_op.alter_column('polish_word',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('english_word',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_card', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('english_word',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('polish_word',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('wrong_count')
        batch_op.drop_column('correct_count')
        batch_op.drop_column('is_known')
        batch_op.drop_column('is_hard')
        batch_op.drop_column('leitner_score')

    # ### end Alembic commands ###
